basePath: /
definitions:
  dto.AccountDetailResponse:
    properties:
      account:
        $ref: '#/definitions/models.Account'
      details:
        $ref: '#/definitions/models.AccountDetail'
    type: object
  dto.AuthenticatedUser:
    properties:
      account:
        $ref: '#/definitions/models.Account'
      token:
        type: string
    type: object
  dto.CreateEmailVerificationRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  dto.DeleteEmailVerificationRequest:
    properties:
      token:
        type: integer
    required:
    - token
    type: object
  dto.ErrorResponse:
    properties:
      errors: {}
      message: {}
      meta_data: {}
      status:
        type: string
    type: object
  dto.ExternalAuthRequest:
    properties:
      oauth_id:
        type: string
      oauth_provider:
        type: string
    required:
    - oauth_id
    - oauth_provider
    type: object
  dto.FileResponse:
    properties:
      created_at:
        type: string
      id:
        type: string
      mime_type:
        type: string
      original_name:
        type: string
      size:
        type: integer
      url:
        type: string
    type: object
  dto.FileResponseSingle:
    properties:
      data:
        $ref: '#/definitions/dto.FileResponse'
      message:
        type: string
      status:
        type: string
    type: object
  dto.FileUploadResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/dto.FileResponse'
        type: array
      message:
        type: string
      status:
        type: string
    type: object
  dto.OptionsRequest:
    properties:
      option_name:
        type: string
      option_values:
        items:
          type: string
        type: array
    required:
    - option_name
    - option_values
    type: object
  dto.ResetPasswordRequest:
    properties:
      new_password:
        type: string
      token:
        type: integer
    required:
    - new_password
    - token
    type: object
  dto.SignInRequest:
    properties:
      email_or_username:
        type: string
      password:
        type: string
    required:
    - email_or_username
    - password
    type: object
  dto.SignUpRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  dto.SuccessResponse-any:
    properties:
      data: {}
      message: {}
      meta_data: {}
      status:
        type: string
    type: object
  dto.SuccessResponse-array_models_RegionCity:
    properties:
      data:
        items:
          $ref: '#/definitions/models.RegionCity'
        type: array
      message: {}
      meta_data: {}
      status:
        type: string
    type: object
  dto.SuccessResponse-array_models_RegionProvince:
    properties:
      data:
        items:
          $ref: '#/definitions/models.RegionProvince'
        type: array
      message: {}
      meta_data: {}
      status:
        type: string
    type: object
  dto.SuccessResponse-dto_AccountDetailResponse:
    properties:
      data:
        $ref: '#/definitions/dto.AccountDetailResponse'
      message: {}
      meta_data: {}
      status:
        type: string
    type: object
  dto.SuccessResponse-dto_AuthenticatedUser:
    properties:
      data:
        $ref: '#/definitions/dto.AuthenticatedUser'
      message: {}
      meta_data: {}
      status:
        type: string
    type: object
  dto.SuccessResponse-models_Account:
    properties:
      data:
        $ref: '#/definitions/models.Account'
      message: {}
      meta_data: {}
      status:
        type: string
    type: object
  dto.SuccessResponse-models_EmailVerification:
    properties:
      data:
        $ref: '#/definitions/models.EmailVerification'
      message: {}
      meta_data: {}
      status:
        type: string
    type: object
  dto.SuccessResponse-models_Options:
    properties:
      data:
        $ref: '#/definitions/models.Options'
      message: {}
      meta_data: {}
      status:
        type: string
    type: object
  dto.UpdateAccountDetailRequest:
    properties:
      avatar:
        type: string
      city:
        type: string
      full_name:
        type: string
      phone_number:
        type: string
      province:
        type: string
      school_name:
        type: string
    type: object
  dto.ValidateVerifyEmailRequest:
    properties:
      email:
        type: string
      token:
        type: integer
    required:
    - email
    - token
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.Account:
    properties:
      created_at:
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      email:
        type: string
      id:
        type: string
      is_detail_completed:
        type: boolean
      is_email_verified:
        type: boolean
      role:
        type: string
      username:
        type: string
    type: object
  models.AccountDetail:
    properties:
      account:
        $ref: '#/definitions/models.Account'
      account_id:
        type: string
      avatar:
        type: string
      city:
        type: string
      full_name:
        type: string
      id:
        type: string
      phone_number:
        type: string
      province:
        type: string
      school_name:
        type: string
    type: object
  models.EmailVerification:
    properties:
      account:
        $ref: '#/definitions/models.Account'
      account_id:
        type: string
      created_at:
        type: string
      expired_at:
        type: string
      id:
        type: string
      is_expired:
        type: boolean
      token:
        type: integer
    type: object
  models.OptionCategory:
    properties:
      id:
        type: integer
      option_name:
        type: string
      option_slug:
        type: string
    type: object
  models.OptionValues:
    properties:
      id:
        type: integer
      option_category_id:
        type: integer
      option_value:
        type: string
    type: object
  models.Options:
    properties:
      option_category:
        $ref: '#/definitions/models.OptionCategory'
      option_values:
        items:
          $ref: '#/definitions/models.OptionValues'
        type: array
    type: object
  models.RegionCity:
    properties:
      code:
        type: string
      full_code:
        type: string
      id:
        type: integer
      name:
        type: string
      province_id:
        type: integer
      type:
        type: string
    type: object
  models.RegionProvince:
    properties:
      code:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: admin@example.com
    name: Abdan Hafidz
  description: Backend API documentation
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Go Boilerplate API
  version: 1.0.0
paths:
  /api/v1/account/me:
    put:
      consumes:
      - application/json
      description: Update detailed information about the authenticated user's account
      parameters:
      - description: Update Account Detail Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateAccountDetailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse-dto_AccountDetailResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Update Account Detail
      tags:
      - Account Detail
  /api/v1/authentication/external-login:
    post:
      consumes:
      - application/json
      description: Authenticate user using external OAuth provider
      parameters:
      - description: External Auth Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ExternalAuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse-dto_AuthenticatedUser'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: External Authentication
      tags:
      - Authentication
  /api/v1/authentication/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and obtain access token
      parameters:
      - description: Sign In Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse-dto_AuthenticatedUser'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: User Login
      tags:
      - Authentication
  /api/v1/authentication/register:
    post:
      consumes:
      - application/json
      description: Register a new user account
      parameters:
      - description: Sign Up Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse-models_Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: User Registration
      tags:
      - Authentication
  /api/v1/email/create-verification:
    post:
      consumes:
      - application/json
      description: Generate a verification token and send it to the specified email
        address
      parameters:
      - description: Create Email Verification Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateEmailVerificationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse-models_EmailVerification'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Create Email Verification Token
      tags:
      - Email Verification
  /api/v1/email/verify:
    post:
      consumes:
      - application/json
      description: Validate the provided verification token for the specified email
        address
      parameters:
      - description: Validate Verify Email Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ValidateVerifyEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse-any'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Validate Email Verification Token
      tags:
      - Email Verification
  /api/v1/files:
    post:
      consumes:
      - multipart/form-data
      description: Upload one or more files to the server
      parameters:
      - description: Upload Context (e.g., image, submission, material)
        in: formData
        name: context
        type: string
      - description: Files to upload (multiple allowed)
        in: formData
        name: files
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.FileUploadResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Upload Files
      tags:
      - Upload
  /api/v1/files/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve file details using its ID
      parameters:
      - description: File ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.FileResponseSingle'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get File by ID
      tags:
      - Upload
  /api/v1/options/create:
    post:
      consumes:
      - application/json
      description: Create multiple options in bulk
      parameters:
      - description: Bulk Options Request
        in: body
        name: request
        required: true
        schema:
          items:
            $ref: '#/definitions/dto.OptionsRequest'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse-any'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Create Bulk Options
      tags:
      - Option
  /api/v1/options/list/{slug}:
    get:
      consumes:
      - application/json
      description: Retrieve option details using its slug
      parameters:
      - description: Option Slug
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse-models_Options'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get Option by Slug
      tags:
      - Option
  /api/v1/options/region/cities:
    get:
      consumes:
      - application/json
      description: Retrieve a list of cities within a specific province
      parameters:
      - description: Province ID
        in: body
        name: request
        required: true
        schema:
          properties:
            province_id:
              type: integer
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse-array_models_RegionCity'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: List Cities by Province
      tags:
      - Region
  /api/v1/options/region/provinces:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all provinces
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse-array_models_RegionProvince'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: List Provinces
      tags:
      - Region
  /api/v1/options/region/seed-cities:
    post:
      consumes:
      - application/json
      description: Seed multiple cities into the system
      parameters:
      - description: Seed Cities Request
        in: body
        name: request
        required: true
        schema:
          items:
            $ref: '#/definitions/models.RegionCity'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse-array_models_RegionCity'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Seed Cities
      tags:
      - Region
  /api/v1/options/region/seed-provinces:
    post:
      consumes:
      - application/json
      description: Seed multiple provinces into the system
      parameters:
      - description: Seed Provinces Request
        in: body
        name: request
        required: true
        schema:
          items:
            $ref: '#/definitions/models.RegionProvince'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse-any'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Seed Provinces
      tags:
      - Region
  /api/v1/payment/callback:
    post:
      consumes:
      - application/json
      description: Receive and process payment status updates from Xendit
      parameters:
      - description: Xendit Callback Payload
        in: body
        name: request
        required: true
        schema:
          additionalProperties: true
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse-any'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Handle Xendit Payment Callback
      tags:
      - Payment
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
